---
- name: Django |  Create Database Tables
  when: syncdb is defined
  django_manage: >
    command=syncdb
    app_path=${django.root}
    settings=${django.settings}
    virtualenv=${django.virtualenv}
  tags:
    - database
    - application
    - django

- name: Django |  Migrate Django database.
  when: migrate is defined
  django_manage: >
    command=migrate
    app_path=${django.root}
    settings=${django.settings}
    virtualenv=${django.virtualenv}
  tags:
    - database
    - update
    - application
    - django

- name: Django | Install Fixtures.
  when: fixtures is defined
  django_manage: >
    command=loaddata
    fixtures=$item
    app_path=${django.root}
    settings=${django.settings}
    virtualenv=${django.virtualenv}
  with_items: django.fixtures
  tags:
    - database
    - fixtures
    - application
    - django
  notify:
    - restart uwsgi
