---
- name: uWsgi | (apt) Install required system packages.
  apt: >
    pkg=${item}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - python-dev
    - python-setuptools
    - python-psycopg2
    - python-virtualenv
    - python-pip
  tags:
    - packages
    - provision

- name: uWsgi | (pip) Install required system packages.
  pip: name=$item
  sudo: yes
  with_items:
    - virtualenv
    - uwsgi
  tags:
    - packages
    - provision

