---
- name: Celery | Install CeleryD supervisor task
  template: >
    src=upstart.celeryd.conf.j2
    dest=/etc/supervisor/conf.d/${project.name}_celeryd.conf
  notify:
    - restart supervisor
  tags:
    - celery

- name: Celery | Install CeleryBeat supervisor task
  template: >
    src=celerybeat.ini.j2
    dest=/etc/supervisor/conf.d/${project.name}_celerybeat.conf
  notify:
    - restart supervisor
  tags:
    - celery
