---
- name: restart uwsgi
  sudo_user: root
  service: >
    name=uwsgi-${project.name}
    state=restarted

- name: reload uwsgi
  sudo_user: root
  service: >
    name=uwsgi-${project.name}
    state=restarted
