---
- name: Add GIS repo
  apt: >
    pkg=python-pycurl
    state=installed
    update-cache=yes

- apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
- apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

- name: Install Packages
  apt: >
    pkg={{ item }}
    state=installed
    update-cache=yes
    force=yes
  with_items:
    - build-essential
    - postgresql
    - python-dev
    - python-setuptools
    - python-psycopg2
    - postgresql-9.3
    - postgresql-9.3-postgis-2.1
    - postgresql-client-9.3
    - libpq-dev
